# Generated by Django 4.0 on 2022-02-13 07:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='URL_Mapping',
            fields=[
                ('url_id', models.CharField(max_length=8, primary_key=True, serialize=False, unique=True)),
                ('original_url', models.URLField(max_length=100, unique=True, validators=[django.core.validators.URLValidator(schemes=['http', 'https'])])),
            ],
            options={
                'verbose_name': 'unique url',
                'db_table': 'url_mapping',
            },
        ),
        migrations.AddIndex(
            model_name='url_mapping',
            index=models.Index(fields=['url_id'], name='url_mapping_url_id_e2c742_idx'),
        ),
    ]
