# Generated by Django 4.0 on 2022-02-13 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('url_shortener', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='url_mapping',
            options={'verbose_name': 'URL Mapping'},
        ),
    ]
